// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/Briefing.tsx": () => import("../components/mockups/dashboard-redesign/Briefing.tsx"),
  "./components/mockups/dashboard-redesign/Cockpit.tsx": () => import("../components/mockups/dashboard-redesign/Cockpit.tsx"),
  "./components/mockups/dashboard-redesign/Current.tsx": () => import("../components/mockups/dashboard-redesign/Current.tsx"),
  "./components/mockups/dashboard-redesign/Scorecard.tsx": () => import("../components/mockups/dashboard-redesign/Scorecard.tsx")
};
